-- CVP Laundry v1.6
-- 1) Editable rules from /admin
-- 2) Per-machine maintenance switch + customer-visible note

alter table public.machines
  add column if not exists is_maintenance boolean not null default false;

alter table public.machines
  add column if not exists maintenance_note text;

create table if not exists public.site_rules (
  id bigint generated by default as identity primary key,
  category text not null default 'general' check (category in ('general', 'dryer')),
  body text not null,
  is_active boolean not null default true,
  sort_order integer not null default 100,
  updated_at timestamptz not null default now()
);

-- Seed the current v1.4/v1.5 rules only when no rules exist yet.
insert into public.site_rules (category, body, is_active, sort_order)
select * from (values
  ('general', 'ตรวจสอบกระเป๋าเสื้อและกางเกง นำเหรียญ กุญแจ กระดาษ และสิ่งของออกก่อนใส่เครื่อง', true, 10),
  ('general', 'ห้ามซักหรืออบผ้าที่เปื้อนน้ำมัน เชื้อเพลิง สารไวไฟ หรือสารเคมีอันตราย', true, 20),
  ('general', 'ห้ามใส่ของแข็ง ของมีโลหะหนัก รองเท้า หรือพรม หากไม่ได้รับอนุญาตจากผู้ดูแล', true, 30),
  ('general', 'ใช้น้ำยาและผงซักฟอกในปริมาณเหมาะสม เพื่อป้องกันฟองล้นและความเสียหายต่อเครื่อง', true, 40),
  ('general', 'ห้ามงัด ดึง หรือพยายามเปิดประตูระหว่างเครื่องกำลังทำงาน', true, 50),
  ('general', 'เมื่อเครื่องทำงานเสร็จ กรุณานำผ้าออกโดยเร็วเพื่อแบ่งปันการใช้งานกับลูกค้าท่านอื่น', true, 60),
  ('dryer', 'ตรวจสอบฉลากการดูแลผ้าก่อนอบ และหลีกเลี่ยงวัสดุที่ละลายหรือเสียรูปจากความร้อน เช่น โฟม ยาง พลาสติก และผ้าที่ระบุว่าห้ามอบด้วยเครื่อง', true, 10),
  ('dryer', 'หากพบเสียง กลิ่น ควัน หรือการทำงานผิดปกติ กรุณาหยุดใช้งานและแจ้งผู้ดูแลทันที', true, 20)
) as seed(category, body, is_active, sort_order)
where not exists (select 1 from public.site_rules);

create index if not exists site_rules_order_idx
  on public.site_rules (category, sort_order, id);

alter table public.site_rules enable row level security;

select machine_no, name, is_maintenance, maintenance_note
from public.machines
order by machine_no;

select id, category, body, is_active, sort_order
from public.site_rules
order by category, sort_order, id;
