create table if not exists public.machines (
  id bigint generated by default as identity primary key,
  machine_no integer not null unique check (machine_no between 1 and 4),
  name text not null,
  machine_type text not null default 'washer' check (machine_type in ('washer', 'dryer')),
  price_baht integer check (price_baht is null or price_baht >= 0),
  status text not null default 'available' check (status in ('available', 'running', 'finished', 'offline')),
  program text,
  started_at timestamptz,
  end_at timestamptz,
  near_finish_notified_at timestamptz,
  finish_notified_at timestamptz,
  is_maintenance boolean not null default false,
  maintenance_note text,
  updated_at timestamptz not null default now()
);

-- Safe migrations for an existing project.
alter table public.machines add column if not exists machine_type text not null default 'washer';
alter table public.machines add column if not exists price_baht integer;
alter table public.machines add column if not exists near_finish_notified_at timestamptz;
alter table public.machines add column if not exists finish_notified_at timestamptz;
alter table public.machines add column if not exists is_maintenance boolean not null default false;
alter table public.machines add column if not exists maintenance_note text;

-- Store profile of the four real machines.
insert into public.machines (machine_no, name, machine_type, price_baht, status)
values
  (1, 'เครื่อง 01', 'washer', 50, 'available'),
  (2, 'เครื่อง 02', 'washer', 40, 'available'),
  (3, 'เครื่อง 03', 'washer', 30, 'available'),
  (4, 'เครื่อง 04', 'dryer', 40, 'available')
on conflict (machine_no)
do update set
  name = excluded.name,
  machine_type = excluded.machine_type,
  price_baht = excluded.price_baht,
  updated_at = now();

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  endpoint text not null unique,
  subscription jsonb not null,
  machine_nos integer[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists push_subscriptions_machine_nos_idx
  on public.push_subscriptions using gin (machine_nos);

-- Browsers never talk directly to these tables. All reads/writes go through server-side Vercel routes.
alter table public.machines enable row level security;
alter table public.push_subscriptions enable row level security;


create table if not exists public.site_announcements (
  id integer primary key check (id = 1),
  title text not null,
  body text not null,
  tone text not null default 'info' check (tone in ('info', 'warning', 'maintenance')),
  is_active boolean not null default true,
  updated_at timestamptz not null default now()
);

insert into public.site_announcements (id, title, body, tone, is_active)
values (
  1,
  'ประกาศจากร้าน',
  'กรุณานำผ้าออกจากเครื่องเมื่อซักหรืออบเสร็จ เพื่อให้ผู้ใช้งานท่านถัดไปสามารถใช้บริการได้ต่อเนื่อง และสามารถติดตามเวลาที่เหลือผ่านหน้า CVP Laundry ได้ตลอดเวลา',
  'info',
  true
)
on conflict (id) do nothing;

alter table public.site_announcements enable row level security;


create table if not exists public.site_rules (
  id bigint generated by default as identity primary key,
  category text not null default 'general' check (category in ('general', 'dryer')),
  body text not null,
  is_active boolean not null default true,
  sort_order integer not null default 100,
  updated_at timestamptz not null default now()
);

insert into public.site_rules (category, body, is_active, sort_order)
select * from (values
  ('general', 'ตรวจสอบกระเป๋าเสื้อและกางเกง นำเหรียญ กุญแจ กระดาษ และสิ่งของออกก่อนใส่เครื่อง', true, 10),
  ('general', 'ห้ามซักหรืออบผ้าที่เปื้อนน้ำมัน เชื้อเพลิง สารไวไฟ หรือสารเคมีอันตราย', true, 20),
  ('general', 'ห้ามใส่ของแข็ง ของมีโลหะหนัก รองเท้า หรือพรม หากไม่ได้รับอนุญาตจากผู้ดูแล', true, 30),
  ('general', 'ใช้น้ำยาและผงซักฟอกในปริมาณเหมาะสม เพื่อป้องกันฟองล้นและความเสียหายต่อเครื่อง', true, 40),
  ('general', 'ห้ามงัด ดึง หรือพยายามเปิดประตูระหว่างเครื่องกำลังทำงาน', true, 50),
  ('general', 'เมื่อเครื่องทำงานเสร็จ กรุณานำผ้าออกโดยเร็วเพื่อแบ่งปันการใช้งานกับลูกค้าท่านอื่น', true, 60),
  ('dryer', 'ตรวจสอบฉลากการดูแลผ้าก่อนอบ และหลีกเลี่ยงวัสดุที่ละลายหรือเสียรูปจากความร้อน เช่น โฟม ยาง พลาสติก และผ้าที่ระบุว่าห้ามอบด้วยเครื่อง', true, 10),
  ('dryer', 'หากพบเสียง กลิ่น ควัน หรือการทำงานผิดปกติ กรุณาหยุดใช้งานและแจ้งผู้ดูแลทันที', true, 20)
) as seed(category, body, is_active, sort_order)
where not exists (select 1 from public.site_rules);

create index if not exists site_rules_order_idx
  on public.site_rules (category, sort_order, id);

alter table public.site_rules enable row level security;
