create table if not exists public.machines (
  id bigint generated by default as identity primary key,
  machine_no integer not null unique check (machine_no between 1 and 4),
  name text not null,
  machine_type text not null default 'washer' check (machine_type in ('washer', 'dryer')),
  price_baht integer check (price_baht is null or price_baht >= 0),
  status text not null default 'available' check (status in ('available', 'running', 'finished', 'offline')),
  program text,
  started_at timestamptz,
  end_at timestamptz,
  near_finish_notified_at timestamptz,
  finish_notified_at timestamptz,
  updated_at timestamptz not null default now()
);

-- Safe migrations for an existing project.
alter table public.machines add column if not exists machine_type text not null default 'washer';
alter table public.machines add column if not exists price_baht integer;
alter table public.machines add column if not exists near_finish_notified_at timestamptz;
alter table public.machines add column if not exists finish_notified_at timestamptz;

-- Store profile of the four real machines.
insert into public.machines (machine_no, name, machine_type, price_baht, status)
values
  (1, 'เครื่อง 01', 'washer', 50, 'available'),
  (2, 'เครื่อง 02', 'washer', 40, 'available'),
  (3, 'เครื่อง 03', 'washer', 30, 'available'),
  (4, 'เครื่อง 04', 'dryer', null, 'available')
on conflict (machine_no)
do update set
  name = excluded.name,
  machine_type = excluded.machine_type,
  price_baht = excluded.price_baht,
  updated_at = now();

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  endpoint text not null unique,
  subscription jsonb not null,
  machine_nos integer[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists push_subscriptions_machine_nos_idx
  on public.push_subscriptions using gin (machine_nos);

-- Browsers never talk directly to these tables. All reads/writes go through server-side Vercel routes.
alter table public.machines enable row level security;
alter table public.push_subscriptions enable row level security;
